services:
  - type: web
    name: cobra-web-craft
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/Thanigachalam98/cobra-web-craft