services:
  - name: cobra-web-craft
    type: web
    runtime: docker
    repo: https://github.com/yourusername/your-repo-name
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    branch: main
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
